name: Planets  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /planets post lambda deploy zip
        uses: postman-open-technologies/planets@main
        with:
            args: zip -qq -r m-s-planets-po.zip planets/post/index.js node_modules
      - name: planets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-planets-po
            zip_file: m-s-planets-po.zip
      - name: /planets get lambda deploy zip
        uses: postman-open-technologies/planets@main
        with:
            args: zip -qq -r m-s-planets-g.zip planets/get/index.js node_modules
      - name: planets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-planets-g
            zip_file: m-s-planets-g.zip
      - name: /planets/{planetid} get lambda deploy zip
        uses: postman-open-technologies/planets@main
        with:
            args: zip -qq -r m-s-planets-planetid-g.zip planets/planetid/get/index.js node_modules
      - name: planets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-planets-planetid-g
            zip_file: m-s-planets-planetid-g.zip
      - name: /planets/{planetid} put lambda deploy zip
        uses: postman-open-technologies/planets@main
        with:
            args: zip -qq -r m-s-planets-planetid-pu.zip planets/planetid/put/index.js node_modules
      - name: planets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-planets-planetid-pu
            zip_file: m-s-planets-planetid-pu.zip
      - name: /planets/{planetid} delete lambda deploy zip
        uses: postman-open-technologies/planets@main
        with:
            args: zip -qq -r m-s-planets-planetid-d.zip planets/planetid/delete/index.js node_modules
      - name: planets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-planets-planetid-d
            zip_file: m-s-planets-planetid-d.zip          